/* Main.ino file generated by New Project wizard
 * Created:   周五 6月 24 2022
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR
 */

//--------------------------------
//名称：继电器控制照明设备
//说明：K1控制继电器
//--------------------------------

#define k1 2              //继电器控制按键
#define relay 4           //继电器控制引脚
#define k1_down() (digitalRead(k1) == HIGH)   //判断k1是否被按下
byte relay_state = HIGH;                       //继电器状态

void setup()
{
    pinMode(k1,INPUT);        //设置k1引脚为输入
    pinMode(relay,OUTPUT);    //设置继电器控制引脚为输出
    digitalWrite(relay,relay_state);   //关闭灯泡
}

void loop()
{
    if(k1_down())            //继电器开关控制
    {
        delay(10);           //延时消抖
        if(k1_down())        //判断是否却是被按下
        {
            relay_state = !relay_state;        //继电器状态取反
            digitalWrite(relay,relay_state);  //输出控制
            while(k1_down());                   //等待按键释放
        }
    }
}
